### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by Talgat0811** [JPLeoRX/youtube-download-cli#4]
youtube-download-cli "https://www.youtube.com/watch?v=oKOtzIo-uYw"
INFO! Started downloading from "https://www.youtube.com/watch?v=oKOtzIo-uYw"
Traceback (most recent call last):
  File "c:\users\amin_stors\desktop\ulutsoft\youtube-download-cli\youtube_download_cli\command_line.py", line 89, in main
    video = youtube.streams.get_highest_resolution()
  File "c:\users\amin_stors\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\pytube\__main__.py", line 296, in streams
    return StreamQuery(self.fmt_streams)
  File "c:\users\amin_stors\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\pytube\__main__.py", line 176, in fmt_streams
    stream_manifest = extract.apply_descrambler(self.streaming_data)
  File "c:\users\amin_stors\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\pytube\__main__.py", line 160, in streaming_data
    self.bypass_age_gate()
  File "c:\users\amin_stors\.pyenv\pyenv-win\versions\3.8.0\lib\site-packages\pytube\__main__.py", line 264, in bypass_age_gate
    raise exceptions.AgeRestrictedError(self.video_id)
pytube.exceptions.AgeRestrictedError: oKOtzIo-uYw is age restricted, and can't be accessed without logging in.
ERROR! Unexpected exception occurred

**Comment by Ivan-Krul** [comment]
it's due to youtube's age restrictive videos, cli tools like pytube can't get access to them.
better to install them using other tools
